name: 'stripe_lap'
version: '1.0.0'
config-version: 2


profile: 'stripe_lap'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

on-run-end:
  #- "{{ log_dbt_results(results) }}"

vars:
  "dbt_date:time_zone": "Asia/Ho_Chi_Minh"

models:
  stripe_lap:
    stripe_stg:
      +materialized: table


        

